name: Build

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-module:
    strategy:
      matrix:
        include:
          - os: macos-latest
            target_os: darwin
            target_arch: amd64
          - os: ubuntu-latest
            target_os: linux
            target_arch: amd64
            container:
                image: ghcr.io/viamrobotics/rdk-devenv:amd64
                options: --platform linux/amd64
          - os: buildjet-8vcpu-ubuntu-2204-arm
            target_os: linux
            target_arch: arm64
            container:
              image: ghcr.io/viamrobotics/rdk-devenv:arm64
              options: --platform linux/arm64
          - os: windows
            target_os: windows
            target_arch: amd64
            container:
                image: ghcr.io/viamrobotics/rdk-devenv:amd64
                options: --platform linux/amd64


    runs-on: ${{ matrix.os }}
    container: ${{ matrix.container }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up build environment
        run: |
            TARGET_OS=${{ target_os }} TARGET_ARCH=${{ target_arch }} make setup

      - name: Make module.tar.gz
        run: |
            TARGET_OS=target_os TARGET_ARCH=target_arch make module.tar.gz
